### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by JayFoxRox** [thelink2012/gta3sc#1]
There is no documentation:

- How to compile this
- How to run this
- What can this even do?

---

Background: I'm currently looking for a tool to disassemble a PC GTA3 main.scm on Linux.
It's important that I get a disassembled version which still includes all opcode numbers as I want to generate statistics about opcode usage etc.

**Comment by JayFoxRox** [comment]
Despite what we discussed on IRC yesterday I still tried to compile it today.

My temporary CMakeLists.txt is (bare with me, never had to write one before and stole it from other projects):

```
cmake_minimum_required(VERSION 2.8)
project(gta3sc)

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++1z")

include_directories(
  deps
  deps/rapidxml
  deps/cppformat
  deps/optional/include
  deps/any/include
  deps/variant/include
  deps/libantlr3c-3.4/include
  deps/libantlr3c-3.4/
)

add_executable(gta3sc
  deps/libantlr3c-3.4/src/antlr3baserecognizer.c
  deps/libantlr3c-3.4/src/antlr3basetreeadaptor.c
  deps/libantlr3c-3.4/src/antlr3basetree.c
  deps/libantlr3c-3.4/src/antlr3bitset.c
  deps/libantlr3c-3.4/src/antlr3collections.c
  deps/libantlr3c-3.4/src/antlr3commontoken.c
  deps/libantlr3c-3.4/src/antlr3commontreeadaptor.c
  deps/libantlr3c-3.4/src/antlr3commontree.c
  deps/libantlr3c-3.4/src/antlr3commontreenodestream.c
  deps/libantlr3c-3.4/src/antlr3convertutf.c
  deps/libantlr3c-3.4/src/antlr3cyclicdfa.c
  #deps/libantlr3c-3.4/src/antlr3debughandlers.c
  deps/libantlr3c-3.4/src/antlr3encodings.c
  deps/libantlr3c-3.4/src/antlr3exception.c
  deps/libantlr3c-3.4/src/antlr3filestream.c
  deps/libantlr3c-3.4/src/antlr3inputstream.c
  deps/libantlr3c-3.4/src/antlr3intstream.c
  deps/libantlr3c-3.4/src/antlr3lexer.c
  deps/libantlr3c-3.4/src/antlr3parser.c
  deps/libantlr3c-3.4/src/antlr3rewritestreams.c
  deps/libantlr3c-3.4/src/antlr3string.c
  deps/libantlr3c-3.4/src/antlr3tokenstream.c
  deps/libantlr3c-3.4/src/antlr3treeparser.c
  src/grammar/autogen/gta3scriptLexer.c
  src/grammar/autogen/gta3scriptParser.c
  src/commands.cpp
  src/main.cpp
  src/parser.cpp
  src/symtable.cpp
  src/system.cpp
)

#target_link_libraries(gtasc
#...)

#install(TARGETS gta3sc RUNTIME DESTINATION bin)
```

However, clang gives various errors about `parser.hpp:138:24: error: extra qualification on member 'child_count'` (more of these for other vars).
gcc gives errors about `std::experimental::optional` / `..::fundamentals_v1`.

(clang version 3.8.0 (tags/RELEASE_380/final) / gcc version 6.1.1 20160501 (GCC); ran on x64 arch linux)

I did not try the proposed changes from your previous messages due to the discouraging results so far which imply compiler differences - not platform issues.

I also wasn't able to run autogen despite having python2-antlr2 installed on arch linux. I guess I could try pip2? (I do not intend to do so anyway, assuming the included files from the repo are fine)

**Comment by thelink2012** [comment]
Should this be closed or there's anything missing?

**Comment by JayFoxRox** [comment]
Very nice! Thanks.

nit: maybe add some indication about the license in the readme or project description?
