### ISSUE TITLE
Strings inside DUMP statements

### ISSUE THREAD

**Issue by thelostt** [thelink2012/gta3sc#115]
Allow this as an extension (perhaps by `-fdump-strings`?):

```
DUMP
"123" 52
ENDDUMP
```

**Comment by thelostt** [comment]
Would it be useful/desirable to have a `\x` escape sequence for strings in DUMP contexts?

**Comment by thelink2012** [comment]
Nah, that should be addressed in general for all strings sometime, without breaking the original design.

**Comment by thelink2012** [comment]
`-fdump` should toggle this without issues, no need for another switch :))
