### ISSUE TITLE
Cannot require more than one file.sc

### ISSUE THREAD

**Issue by thiagocodero** [thelink2012/gta3sc#121]
So I tried to figure out how to require files for separating functions/blocks I did:

main.sc
```sc
SCRIPT_START
REQUIRE a.sc
REQUIRE b.sc
NOP
{
    main:
    WAIT 0

    IF IS_BUTTON_PRESSED PAD1 CROSS
        CLEO_CALL afunc 0
    ENDIF

    IF IS_BUTTON_PRESSED PAD1 CIRCLE
        CLEO_CALL bfunc 0
    ENDIF

    GOTO main
}

SCRIPT_END
```

a.sc
```sc
{
    afunc:
    PRINT_STRING_NOW "SHOWA" 1000
    CLEO_RETURN 0
}
```

b.sc
```sc
{
    bfunc:
    PRINT_STRING_NOW "SHOWB" 1000
    CLEO_RETURN 0
}
```

Pressing Both X or O shows "SHOWA"
[arquivos-cleo.zip](https://github.com/thelink2012/gta3sc/files/4670947/arquivos-cleo.zip)

I searched the internet a lot, but I couldn't make it work, I'm making a root cheat menu and I only managed to use 2 files and no more, so they are getting too big, I contacted grinch_ and he analyzed it so told me that it seems to be a bug, could you take a look? I will be grateful!

**Comment by thelink2012** [comment]
Yes, that sems like a bug. Thank you for reporting, I'll investigate and fix ASAP.

**Comment by thelink2012** [comment]
Fixed in the latest release =)
