### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by JustAShadow777** [thelink2012/gta3sc#122]
I'm tired of Cmake errors..
Can you make a more detalied guide of how to install this compiler?

**Comment by thelink2012** [comment]
Hi,

Could you be more descriptive? What kind of error do you get? Which platform?

Thanks

**Comment by JustAShadow777** [comment]
Hi,

Sorry, I was nervous. Thanks for responding.

I'm using windows and I got tired of CMake compiler errors. After like 6 hours I fixed these and now I don't know how to build MakeFiles with Make. I tried:
### cd C:\Program Files (x86)\GnuWin32\bin
### make C:\Users\TheSu\Desktop\gta3sc-master

but the response was the same for all folders:

### make: Nothing to be done for `C:\Users\TheSu\Desktop\gta3sc-master'.

Thanks!

**Comment by thelink2012** [comment]
You can download pre-compiled binaries for Windows at https://github.com/thelink2012/gta3sc/releases. Any particular reason you wish to build it from scratch, if I may ask?

**Comment by JustAShadow777** [comment]
I tried these too, but the code simply don't work for a reason, cleo don't load it..

**Comment by thelink2012** [comment]
Seems like you are compiling for the wrong target game. This compiles fine by using `gta3sc modu.sc --config=gtasa --guesser --cs`.

I also recommend the [VSCode extension](https://marketplace.visualstudio.com/items?itemName=thelink2012.gta3script) in order to simplify things out.

Cheers

**Comment by JustAShadow777** [comment]
Hi!

It returns:

C:\Users\TheSu\Desktop\gta3sc>gta3sc C:\Users\TheSu\Desktop\modu.sc --config=gtasa --guesser
C:/Users/TheSu/Desktop/modu.sc:14:5: error: unknown command
 AND IS_KEY_PRESSED VK_KEY_Y
     ^~~~~~~~~~~~~~
C:/Users/TheSu/Desktop/modu.sc:34:11: error: unknown command
     WHILE IS_KEY_PRESSED VK_KEY_Y
           ^~~~~~~~~~~~~~
C:/Users/TheSu/Desktop/modu.sc: error: cannot use SCRIPT_START in main scripts
gta3sc: compilation failed

**Comment by thelink2012** [comment]
Add `--cs` (as in my command above) in order to tell you are compiling a CLEO script (`IS_KEY_PRESSED` is a CLEO command).

**Comment by JustAShadow777** [comment]
It works!
Thanks you so much!

**Comment by thelink2012** [comment]
No problem, glad to help :)
