### ISSUE TITLE
High-level decompiler

### ISSUE THREAD

**Issue by thelink2012** [thelink2012/gta3sc#13]

**Comment by thelink2012** [comment]
Some nice links:
+ **Theory for Basic Blocks, Control Flow and Dominance:** http://www.sable.mcgill.ca/~hendren/621/ControlFlowAnalysis_Handouts.pdf
+ **Practical Implementation (skips much of the theory)**: http://www.backerstreet.com/decompiler/introduction.htm (go to Architecture to skip obvious things).

**Comment by thelink2012** [comment]
Not easy...

The feature-flow branch was a failed try to implement a high-level decompiler, it won't be merged to master at this point, the source is too confusing and doesn't work properly (and never will).

**Comment by x87** [comment]
I'm in slow progress on making my own implementation of the subject. Hope to finish it anytime in future https://github.com/x87/scout.js

**Comment by thelink2012** [comment]
Closing this issue because it's not something I can support at this time.
