### ISSUE TITLE
Desc field for Opcode 0x129 is confusing

### ISSUE THREAD

**Issue by JayFoxRox** [thelink2012/gta3sc#18]
Hey, danhedron of OpenRW noticed that one of the commands had confusing descriptions.

[Affected GTA III version](https://github.com/thelink2012/gta3sc/blob/0b6f18cbf6981910a0fc869c8d8c3b51f2a771b2/config/gta3/commands.xml#L1806)
[Affected GTA VC version](https://github.com/thelink2012/gta3sc/blob/master/config/gtavc/commands.xml#L1805)

The XML portion in question is

```
        <Arg Type="INT" Desc="Ped type" Entity="CAR"/>
        <Arg Type="INT" Desc="Model ID" Enum="PEDTYPE"/>
        <Arg Type="INT" Desc="Car/vehicle" Enum="CARPEDMODEL"/>
```

where a mismatch between `Desc` and `Entity` / `Enum` occurs.

---

```
        <Arg Type="INT" Desc="Car/vehicle type" Entity="CAR"/>
        <Arg Type="INT" Desc="Ped" Enum="PEDTYPE"/>
        <Arg Type="INT" Desc="Model ID" Enum="CARPEDMODEL"/>
```

is probably better.

Note that the [GTA SA version](https://github.com/thelink2012/gta3sc/blob/master/config/gtasa/commands.xml#L1805) of the command is less complete so the problem doesn't exist there yet.

**Comment by thelink2012** [comment]
Fixed by #43
